openapi: 3.0.3
info:
    title: Inventory Management Web App
    description: >-
        This is a Inventory Management Web App : Inventory Management Web App based
        on the OpenAPI 3.0 specification.
    contact:
        email: tambe.tanush.comp@kgce.edu.in
    version: 1.0.11
servers:
    - url: http://127.0.0.1:5000
tags:
    - name: Item
      description: Perform operation on a single item
    - name: ItemList
      description: Perform operation on multiple items
paths:
    /api/item/<int:itemid>:
        get:
            tags:
                - Item
            summary: Get information about an Item
            description: Get information about an Item
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Item"
                "404":
                    description: Item not found
        put:
            tags:
                - Item
            summary: Update an existing Item
            description: Update filds of an already existing Item
            parameters:
                - name: name
                  in: query
                  description: Name of item that needs to be updated
                  schema:
                      type: string
                      example: "Name of item"
                - name: partno
                  in: query
                  description: partno of Item that needs to be updated
                  schema:
                      type: string
                      example: "AB1001"
                - name: category
                  in: query
                  description: category of Item that needs to be updated
                  schema:
                      type: integer
                      example: 1
                - name: description
                  in: query
                  description: description of Item that needs to be updated
                  schema:
                      type: string
                      example: "Description of item"
                - name: quantity
                  in: query
                  description: quantity of Item that needs to be updated
                  schema:
                      type: integer
                      example: 300
                - name: price
                  in: query
                  description: price of Item that needs to be updated
                  schema:
                      type: number
                      example: 2000.50
            requestBody:
                description: Update an existing Item
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Item"
                required: true

            responses:
                "200":
                    description: Successful operation
                "404":
                    description: Item not found
        delete:
            tags:
                - Item
            summary: Deletes an existing Item
            description: Deletes an existing Item
            responses:
                "200":
                    description: Item Successfully Deleted
                "404":
                    description: Item not found
    /api/item/list:
        get:
            tags:
                - ItemList
            summary: Get information about all Item
            description: Get information about all Item
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Item"
        post:
            tags:
                - ItemList
            summary: Creates a new Item
            description: "Create a new Item with given fields"
            parameters:
                - name: name
                  in: query
                  description: Name of item that needs to be updated
                  schema:
                      type: string
                      example: "Name of item"
                - name: partno
                  in: query
                  description: partno of Item that needs to be updated
                  schema:
                      type: string
                      example: "AB1001"
                - name: category
                  in: query
                  description: category of Item that needs to be updated
                  schema:
                      type: integer
                      example: 1
                - name: description
                  in: query
                  description: description of Item that needs to be updated
                  schema:
                      type: string
                      example: "Description of item"
                - name: quantity
                  in: query
                  description: quantity of Item that needs to be updated
                  schema:
                      type: integer
                      example: 300
                - name: price
                  in: query
                  description: price of Item that needs to be updated
                  schema:
                      type: number
                      example: 2000.50
            responses:
                "201":
                    description: Successful operation
components:
    schemas:
        Item:
            type: object
            properties:
                itemid:
                    type: integer
                    format: int64
                    example: 10
                name:
                    type: string
                    example: "Name of item"
                description:
                    type: string
                    example: "Description of item"
                partno:
                    type: string
                    example: "AB1001"
                category:
                    type: integer
                    format: int64
                    example: 1
                price:
                    type: number
                    format: float
                    example: 2000.50
                quantity:
                    type: integer
                    format: int64
                    example: 300
    requestBodies:
        Item:
            description: Item object that needs to be added to the store
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Item"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Item"
